VMS/urls.py
from django.urls import path
from .views import (VehicleListView, VehicleDataCreateView, VehicleDataUpdateView,
                    VehicleDataDeleteView)

app_name = 'vms'
urlpatterns = [
    path('home/', view=VehicleListView.as_view(), name='vehicle-list'),
    path('create/', view=VehicleDataCreateView.as_view(), name='vehicle-save'),
    path('vehicle/<int:pk>/update/', view=VehicleDataUpdateView.as_view(), name='vehicle-update'),
    path('vehicle/<int:pk>/delete/', view=VehicleDataDeleteView.as_view(), name='vehicle-delete'),
]

djangoTEST_shevin_KSolutions/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_view, logout_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('VMS.urls', namespace='vms')),
    path('login/', login_view, name ='login'),
    path('logout/', logout_view, name ='logout'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VMS/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse


# Create your models here.

rule = RegexValidator(r'^[A-Za-z]{2}[\s-]{0,1}[0-9]{2}[\s-]{0,1}[A-Za-z]{1,2}[\s-]{0,1}[0-9]{4}$', 'Only Numbers & Characters')

class vms_records(models.Model):
    TWO     = 'TWO WHEELER'
    THREE   = 'THREE WHEELER'
    FOUR    = 'FOUR WHEELER'
      
    TYPE_CHOICES = (
          (TWO, 'Two'),
          (THREE, 'Three'),
          (FOUR, 'Four'),
      )
    
    v_number = models.CharField(max_length=200,null=True,blank=True, validators=[rule], verbose_name="Vehicle Number")
    v_type  = models.CharField(choices=TYPE_CHOICES,max_length=200,null=True,blank=True, verbose_name="Vehicle Type")
    v_model = models.CharField(max_length=500,null=True,blank=True, verbose_name="Vehicle Model")
    v_description = models.TextField(max_length=1000,null=True,blank=True, verbose_name="Vehicle Description")
    created  = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, blank=True, null=True) 


    def __str__(self):
        return f"VEHICLE NO. >>{self.v_number}"

    class Meta:
        ordering = ('-created',)
    

VMS/forms.py
from django import forms
from .models import vms_records

class VehicleDataForm(forms.ModelForm):
    class Meta:
        model = vms_records
        fields = ('v_number', 'v_type','v_model','v_description')

VMS/views.py
from typing import Dict
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import redirect, render
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.edit import UpdateView, DeleteView
from .models import vms_records
from .forms import VehicleDataForm
from .utils import is_super_admin, is_admin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin



# List All the Vehicle Data | ListView
class VehicleListView(LoginRequiredMixin, ListView):
    model = vms_records
    template_name = 'home.html'
    context_object_name = "list_obj"

    def get_context_data(self, **kwargs):
        context = super(VehicleListView, self).get_context_data(**kwargs)
        context.update({
            'l1_type': self.request.user.is_superuser,
            'l2_type': self.request.user.groups.filter(name='Admin').exists(),
        })
        return context


# Create Vehicle Data | CreateView
class VehicleDataCreateView(UserPassesTestMixin, LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = vms_records
    form_class = VehicleDataForm
    template_name ="create_vehicle.html"
    success_url = '/home'

    def test_func(self):
        user = self.request.user
        return is_super_admin(user)
    
    def handle_no_permission(self):
        return redirect("vms:vehicle-list")
    
    def get_success_message(self, cleaned_data):
        return f"Entry for Vehicle No.{cleaned_data['v_number']} created Successfully"




# Update Vehicle Data | UpdateView
class VehicleDataUpdateView(UserPassesTestMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = vms_records
    form_class = VehicleDataForm
    template_name = "update_vehicle.html"
    success_url = '/home'

    def test_func(self):
        user = self.request.user
        return is_super_admin(user) or is_admin(user)

    def handle_no_permission(self):
        return redirect("vms:vehicle-list")

    def get_success_message(self, cleaned_data):
        return f"Entry Updated for Vehicle No.{cleaned_data['v_number']}"




# Delete Vehicle Data | DeleteView
class VehicleDataDeleteView(UserPassesTestMixin, LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = vms_records
    template_name ="confirm.html"
    success_url = '/home'


    def test_func(self):
        user = self.request.user
        return is_super_admin(user)

    def handle_no_permission(self):        
        return redirect("vms:vehicle-list")

    def get_success_message(self, cleaned_data):
        return f"Entry Deleted Successfully"

djangoTEST_shevin_KSolutions/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm


def logout_view(request):
    logout(request)
    return redirect('login')


def login_view(request):
    error_message = None
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username, password = password)
            if user is not None:
                login(request, user)

                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                else:
                    return redirect('vms:vehicle-list')
        else:
            error_message = 'Something went wrong'
        
    
    context ={
        'form': form,
        'error_message': error_message
    }
    
    return render(request,'auth/login.html',context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'icon.png' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- Dropzone js -->

    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
    
    {% comment %} 
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script> {% endcomment %}

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Vehicle Management System | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
  </body>
</html>

templates/confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load static %}
{% block scripts %}

{% endblock scripts %}


{% block title %}

DELETE Data?
{% endblock title %}


{% block content %}


  <div class="alert alert-warning" role="alert">
        <b>Warning! Deletion is irreversible!</b>      
  </div>


{% comment %} <hr> {% endcomment %}

<h2>Confirm Delete</h2>
<p>Are you sure you want to delete the entry "{{ object }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Delete</button>
</form>



{% endblock content %}

templates/create_vehicle.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load static %}
{% block scripts %}

{% endblock scripts %}


{% block title %}
Add Vehicle Details

{% endblock title %}


{% block content %}

{% comment %} <hr> {% endcomment %}


{% csrf_token %}

<form method="post" action="{% url 'vms:vehicle-save' %}">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-success">Click to Submit</button>
</form>

{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load static %}
{% block scripts %}

{% endblock scripts %}


{% block title %}
List All Vehicle Info

{% endblock title %}


{% block content %}

{% comment %} <hr> {% endcomment %}

{% if messages %}
  <div class="alert alert-success" role="alert">
    {% for message in messages %}

        <b>{{message}}</b>
      
    {% endfor %}
  </div>

{% endif %}


{% for i in list_obj%}

<div class="row">
    <div class="col-lg-6 mb-4" style="margin-left: 20em;">


        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-md-4">

                {% if i.v_type == 'FOUR WHEELER' %}
                <img src="/media/4_w.jpg" class="img-fluid rounded-start" style="max-width: 107%;height: 9em;" alt="4 Wheeler">
                {% elif i.v_type == 'THREE WHEELER' %}
                <img src="/media/3_w.jpg" class="img-fluid rounded-start" style="max-width: 107%;height: 9em;" alt="3 Wheeler">
                {% elif i.v_type == 'TWO WHEELER' %}
                <img src="/media/2_w.jpg" class="img-fluid rounded-start" style="max-width: 107%;height: 9em;" alt="2 Wheeler">
                {% endif %}
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{{i.v_type}}</h5>
                  <h6 class="card-subtitle mb-2 text-body-secondary">{{i.pk}} No.{{i.v_number}}</h6>
                  <p class="card-text">{{i.v_model}}</p>
                  <p class="card-text">Description:: {{i.v_description}}</p>
                  {% if l1_type %}
                    <a href="{% url "vms:vehicle-update" pk=i.pk %}" class="btn btn-warning">Edit</a>

                    <a href="{% url "vms:vehicle-delete" pk=i.pk %}" class="btn btn-danger">Delete</a>
                 {% elif l2_type %}
                    <a href="{% url "vms:vehicle-update" pk=i.pk %}" class="btn btn-primary">Edit</a>
                 {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
</div>

{% endfor %}


{% endblock content %}

templates/navbar.html
{% load static %}

{% comment %} Pre-defining Paths {% endcomment %}

{% url 'vms:vehicle-list' as path_to_home %}
{% url 'vms:vehicle-save' as path_to_create %}



<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/home"><img src="/media/favicon.ico" class="logo-sm"></a>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link
          {% if request.path == path_to_home %}
          active
          {% endif %}
          " 
          href="{{path_to_home}}">Home</a>
        </li>

        {% if request.user.is_superuser %}

          <li class="nav-item">
            <a class="nav-link 
            {% if request.path == path_to_create %}
            active
            {% endif %}
            " 
            href="{{path_to_create}}">Add Data</a>
          </li>

        {% endif %}

    </ul>
    </div>


    {% comment %} DROP down mein Blue color is highlight {% endcomment %}
    {% if request.user.is_authenticated %}
      <div class="nav-item dropdown">
        <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          {{request.user}}
        </div>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

            
          <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
        </ul>
      </div>
    {% endif %}
  </div>
</nav>

templates/update_vehicle.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load static %}
{% block scripts %}

{% endblock scripts %}


{% block title %}
Update Vehicle Details

{% endblock title %}


{% block content %}

{% comment %} <hr> {% endcomment %}



<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-success">Click to Submit</button>
</form>

{% endblock content %}